import React, {useMemo, useState} from 'react';
import products from './data/products';

const money = value => `₹${value.toLocaleString('en-IN')}`;
const API = process.env.REACT_APP_API_URL || 'http://localhost:5000/api';

function App(){
  const [category,setCategory]=useState('All'); const [query,setQuery]=useState(''); const [cart,setCart]=useState([]); const [checkout,setCheckout]=useState(false); const [notice,setNotice]=useState('');
  const [form,setForm]=useState({name:'',phone:'',address:'',city:'',pincode:''});
  const filtered=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&`${p.name} ${p.type} ${p.color}`.toLowerCase().includes(query.toLowerCase())),[category,query]);
  const add=(p)=>{setCart(c=>{const found=c.find(x=>x.id===p.id);return found?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]});setNotice(`${p.name} added to your bag`);setTimeout(()=>setNotice(''),2200)};
  const change=(id,delta)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(0,x.qty+delta)}:x).filter(x=>x.qty));
  const total=cart.reduce((sum,x)=>sum+x.price*x.qty,0); const count=cart.reduce((sum,x)=>sum+x.qty,0);
  const submit=async e=>{e.preventDefault(); if(!cart.length)return; const payload={customer:form,items:cart.map(({id,name,price,qty,size})=>({id,name,price,qty,size})),total}; try{const r=await fetch(`${API}/orders`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); if(!r.ok)throw new Error();}catch(err){console.warn('API unavailable; completing demo checkout locally.')} setCart([]);setCheckout(false);setForm({name:'',phone:'',address:'',city:'',pincode:''});setNotice('Order placed successfully! We will call to confirm delivery.');setTimeout(()=>setNotice(''),5000)};
  return <div className="app"><header><div className="topline">Free delivery on orders over ₹2,000 · Easy 7-day exchanges</div><nav><a className="brand" href="#home">MODE<span>&</span>THREAD</a><div className="links"><button onClick={()=>setCategory('All')}>Shop all</button><button onClick={()=>setCategory('Men')}>Men</button><button onClick={()=>setCategory('Women')}>Women</button></div><div className="nav-actions"><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search styles"/></label><button className="bag" onClick={()=>setCheckout(true)}>Bag <b>{count}</b></button></div></nav></header>
  <main id="home"><section className="hero"><div><p className="eyebrow">THE EVERYDAY EDIT · 2026</p><h1>Dress for the life<br/><em>you’re living.</em></h1><p className="hero-copy">Thoughtful, easy-to-wear pieces for every mood, moment and you.</p><button className="dark-btn" onClick={()=>document.getElementById('collection').scrollIntoView({behavior:'smooth'})}>Explore collection <span>→</span></button></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=85" alt="Fashion model wearing a neutral outfit"/><div className="hero-note">New season<br/><strong>Spring / Summer</strong></div></div></section>
  <section className="intro"><p className="eyebrow">CURATED FOR YOU</p><h2>Good clothes. Better days.</h2><p>Made for movement, made to last, made to feel like yourself.</p></section>
  <section id="collection" className="collection"><div className="section-head"><div><p className="eyebrow">SHOP THE EDIT</p><h2>New favourites</h2></div><div className="filters">{['All','Men','Women'].map(x=><button className={category===x?'active':''} key={x} onClick={()=>setCategory(x)}>{x}</button>)}</div></div><div className="grid">{filtered.map(p=><article className="card" key={p.id}><div className="product-image"><img src={p.image} alt={p.name}/>{p.badge&&<span>{p.badge}</span>}<button className="quick" onClick={()=>add(p)}>Add to bag</button></div><div className="product-info"><div><h3>{p.name}</h3><p>{p.category} · {p.color}</p></div><strong>{money(p.price)}</strong></div></article>)}</div>{!filtered.length&&<p className="empty">No styles match your search.</p>}</section>
  <section className="promise"><div><span>01</span><h3>Wear everywhere</h3><p>Versatile silhouettes that move with your everyday.</p></div><div><span>02</span><h3>Thoughtfully chosen</h3><p>Quality fabrics and details you’ll come back to.</p></div><div><span>03</span><h3>Here for you</h3><p>Message us anytime for fit and styling help.</p></div></section></main>
  <footer><div className="brand">MODE<span>&</span>THREAD</div><p>Modern essentials for men and women.</p><a href="https://wa.me/919999999999" target="_blank" rel="noreferrer">Chat with us on WhatsApp ↗</a><small>© 2026 Mode & Thread. Replace the demo contact number before launch.</small></footer>
  {notice&&<div className="toast">{notice}</div>}
  {checkout&&<div className="overlay" onClick={e=>e.target===e.currentTarget&&setCheckout(false)}><aside className="drawer"><button className="close" onClick={()=>setCheckout(false)}>×</button><h2>Your bag <small>({count} items)</small></h2>{!cart.length?<div className="empty-bag"><p>Your bag is waiting for something good.</p><button className="dark-btn" onClick={()=>setCheckout(false)}>Continue shopping</button></div>:<><div className="bag-items">{cart.map(x=><div className="bag-item" key={x.id}><img src={x.image} alt=""/><div><h3>{x.name}</h3><p>{money(x.price)}</p><div className="quantity"><button onClick={()=>change(x.id,-1)}>−</button><span>{x.qty}</span><button onClick={()=>change(x.id,1)}>+</button></div></div></div>)}</div><div className="total"><span>Subtotal</span><strong>{money(total)}</strong></div><form onSubmit={submit}><h3>Delivery details</h3><input required placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required pattern="[0-9+ -]{8,}" placeholder="Phone number" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><textarea required placeholder="Full delivery address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><div className="two"><input required placeholder="City" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/><input required placeholder="PIN code" value={form.pincode} onChange={e=>setForm({...form,pincode:e.target.value})}/></div><button className="dark-btn full">Place cash-on-delivery order <span>→</span></button></form></>}</aside></div>}
  <a className="whatsapp" href="https://wa.me/919999999999" target="_blank" rel="noreferrer">☏</a></div>
}
export default App;
